Wykks/Untamed-Now-Playing-Next

content.js

Fixed for new soundcloud layout

Soundcloud Update

---

_locales/en/messages.json
lib/pages/options.js
lib/proxy.js
options.html

I've noticed a problem with xml output where it isn't encoding special characters (like &), which caused parsing to fail. This should properly encode the values.
This will also add JSON as an output format (for use in other programs which wish to have another output option)

Properly escape xml values and add JSON output

---

data/content.js

They just changed ids for play button and track name label.

Fix play.google.com (#49)

---

data/common/websites-support/websites/openfm.js

Open.fm changed class attribute.

fix open.fm

---

README.md

fix README.md to represent #106 and #108 PR

---

data/common/websites-support/websites/radiotunes.js
index.js

As requested in #111 
- works both on ordinary page and pop-up player
- also downloads album art

Add www.radiotunes.com support (iss#111)

---

data/common/options/sites.json
data/common/websites-support/websites/radioultra.js
index.js

- Fix domain name (from _http://www.radioultra.ru/player_ to _http://player.radioultra.ru_)
- Fix selectors
- Add artwork support

Fix "radioultra.ru"

---

data/common/websites-support/websites/radioyandex.js

Fixed radio.yandex.ru

---

data/common/websites-support/websites/radioyandex.js

Is it ok to use unsafeWindow?
By the wat all features have been implemented.

Moved from page parsing to js variables

---

data/common/websites-support/websites/zvooq.js
index.js

Add Zvooq.com support

---

data/common/options/sites.json
data/common/websites-support/websites/plex.js

Fix plex.tv album title & art

---

README.md
data/common/options/sites.json
data/common/websites-support/websites/radiobells.js
index.js

Add radiobells.com support

---

data/common/options/sites.json
data/common/websites-support/websites/openwhyd.js
index.js

Added some code to now also support the website openwhyd.org. I'd like you to add it to your version of the app if possible.

Added support for openwhyd.org

---

data/common/options/sites.json
data/common/websites-support/websites/musicyandex.js

fix Yandex Music

---

README.md
data/common/options/sites.json
data/common/websites-support/websites/tidal.js
index.js

add Tidal support

---

data/common/websites-support/websites/pandora.js

#129
Now should work with latest Pandora version.

fix Pandora.com support

---

data/common/websites-support/websites/pandora.js

Improves Pandora usability as mentioned in #161

Change a selector from where Pandora grabs data

---

data/common/websites-support/websites/youtube.js

Fix for new Youtube.
Keep in mind, old Youtube design will no longer work.
References #148, #163 and #165

Update to work with new Youtube

---

data/common/options/sites.json
data/common/websites-support/websites/plex.js

Plex changed its selectors to some horrible ones, but it seems to work now.
Unfortunately, **artworks are missing now**, so if someone will find out how to fix this - could be great.
References #163

Fix Plex support

---

data/common/websites-support/websites/spotify.js

This looks ugly, but works pretty neat with both single and multiple artists.
References #170

Fix parsing multiple artists

---

data/common/options/app.js
data/common/options/changelog.json
data/common/websites-support/websites/pandora.js
package.json

Fix pandora.com
